// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5e6nzxF0tSluEtApTX4C3naTyvyQ0idM',
    appId: '1:685765647241:web:c4769cbd2964176f2a5f58',
    messagingSenderId: '685765647241',
    projectId: 'saferoad-57472',
    authDomain: 'saferoad-57472.firebaseapp.com',
    databaseURL: 'https://saferoad-57472-default-rtdb.firebaseio.com',
    storageBucket: 'saferoad-57472.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCusbjfgSS_F0pyYUu7LofJyQcZEV5A7o',
    appId: '1:685765647241:android:59f65438180e2bce2a5f58',
    messagingSenderId: '685765647241',
    projectId: 'saferoad-57472',
    databaseURL: 'https://saferoad-57472-default-rtdb.firebaseio.com',
    storageBucket: 'saferoad-57472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr2ZhIvIwMJTSfBDB4TtpyMqHikrcqXnA',
    appId: '1:685765647241:ios:5bc4c595386d8fa82a5f58',
    messagingSenderId: '685765647241',
    projectId: 'saferoad-57472',
    databaseURL: 'https://saferoad-57472-default-rtdb.firebaseio.com',
    storageBucket: 'saferoad-57472.appspot.com',
    iosClientId: '685765647241-jn58hs21lc45mehtkfsn7ju0mbo8tmee.apps.googleusercontent.com',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr2ZhIvIwMJTSfBDB4TtpyMqHikrcqXnA',
    appId: '1:685765647241:ios:1a04e6a5643c71732a5f58',
    messagingSenderId: '685765647241',
    projectId: 'saferoad-57472',
    databaseURL: 'https://saferoad-57472-default-rtdb.firebaseio.com',
    storageBucket: 'saferoad-57472.appspot.com',
    iosClientId: '685765647241-96ln2brrtmrk91nsojepafejrrke687n.apps.googleusercontent.com',
    iosBundleId: 'com.example.appProject.RunnerTests',
  );
}
